config/routes.rb
Dp::Application.routes.draw do

resources :groups
resources :associates
resources :companies
resources :locations
resources :searches
resources :sessions, only: [:new, :create, :destroy]

root :to => "pages#home"

match '/team', to: 'pages#team'
match '/offices', to: 'pages#offices'
match '/signin', to: 'sessions#new'
match '/signup',  to: 'associates#new'
match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :nickname
  has_many :associates
  has_many :searches, :through => :associates
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_filter :signed_in_associate, only: [:index, :show]
  before_filter :admin_associate,     only: :destroy

  def index
  	@groups = Group.all
  end

  def show
  	@group = Group.find(params[:id])
  	@associates = @group.associates
		@searches = @group.searches
  end

  private

      def signed_in_associate
        unless signed_in?
          store_location
          redirect_to signin_url, notice: "Please sign in."
        end
      end

      def correct_associate
      @associate = Associate.find(params[:id])
      redirect_to(root_path) unless current_associate?(@associate)
      end

      def admin_associate
      redirect_to(root_path) unless current_associate.admin?
      end
      
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group.html.erb
<tr>
	<td><%= link_to group.name, group %></td>
	<td><%= group.associates.count %></td>
	<td><%= group.searches.count %></td>
</tr>

app/views/groups/index.html.erb
<% provide(:title, 'All Teams') %>
<h1>All Teams</h1>

<table class="table table-striped">
	<thead>
		<th>Name</th>
		<th>Team Members</th>
		<th>Searches</th>
	</thead>

	<tbody>
		<%= render @groups %>
	</tbody>
</table>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<h1><%= @group.nickname %></h1>

<!--<table class="table table-striped">
	<thead>
		<th>Name</th>
	</thead>

	<tbody>
		<%= render @associates %>
	</tbody>
</table>-->

<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Team Members (<%= @group.associates.count %>)</a></li>
    <li><a href="#tab2" data-toggle="tab">Team Searches (<%= @group.searches.count %>)</a></li>
    <li><a href="#tab3" data-toggle="tab">Team Analytics</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
    	<% if !@group.associates.empty? %>
      <table class="table table-striped">
				<thead>
					<th>Name</th>
					<th>Email</th>
					<th>Team</th>
				</thead>
				<tbody>
					<%= render @associates %>
				</tbody>
			</table>
			<% else %>
				<%= link_to 'You must add an associate', signup_path %>
			<% end %>
    </div>
    <div class="tab-pane" id="tab2">
    	<% if !@group.searches.empty? %>
      <table class="table table-striped">
				<thead>
					<th>Name</th>
					<th>Position</th>
				</thead>
				<tbody>
					<%= render @searches %>
				</tbody>
			</table>
			<% else %>
				<%= link_to 'You must add a search.', new_search_path %>
			<% end %>
    </div>
    <div class="tab-pane" id="tab3">
      <h1><%= @group.nickname %>'s Analytics</h1>
	      <div class="row span4">
	      	<div class="well">
	      		<P>WELL 1</p>
	      	</div>
	      </div>
	      <div class="row span4">
	      	<div class="well">
	      		<P>WELL 1</p>
	      	</div>
	      </div>
    </div>
  </div>
</div>