config/routes.rb
Dp::Application.routes.draw do

resources :groups
resources :associates
resources :companies
resources :locations
resources :searches
resources :sessions, only: [:new, :create, :destroy]

root :to => "pages#home"

match '/team', to: 'pages#team'
match '/offices', to: 'pages#offices'
match '/signin', to: 'sessions#new'
match '/signup',  to: 'associates#new'
match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :short_description, :website
  has_many :locations
  has_many :searches

  accepts_nested_attributes_for :locations
  accepts_nested_attributes_for :searches

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :signed_in_associate, only: [:new, :create, :index, :edit, :update, :show]
  before_filter :admin_associate,     only: :destroy

  def new
  	@company = Company.new
  end

  def show
  	@company = Company.find(params[:id])
    @searches = @company.searches
    @locations = @company.locations
  end

  def index
  	@companies = Company.all
  end

  def edit
  	@company = Company.find(params[:id])
  end

  def create
    @company = Company.new(params[:company])
    if @company.save
      flash[:success] = "Successfully created a new company!"
      redirect_to @company
    else
      render 'new'
    end
  end

  def update
    @company = Company.find(params[:id])
    if @company.update_attributes(params[:company])
      flash[:success] = "Company updated"
      redirect_to @company
    else
      render 'edit'
    end
  end

  def destroy
    Company.find(params[:id]).destroy
    flash[:success] = "Company destroyed."
    redirect_to companies_url
  end


    private

      def signed_in_associate
        unless signed_in?
          store_location
          redirect_to signin_url, notice: "Please sign in."
        end
      end

      def correct_associate
      @associate = Associate.find(params[:id])
      redirect_to(root_path) unless current_associate?(@associate)
      end

      def admin_associate
      redirect_to(root_path) unless current_associate.admin?
      end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<tr>
	<td><%= link_to company.name, company %></td>
	<td><%= company.website %></td>
	<td><%= company.short_description %></td>
	<td><%= link_to 'Show', company %></td>
	<% if current_associate.admin? %>
		<td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Delete', company, method: :delete, data: { confirm: "You sure?" } %></td>
  <% end %>
</tr>

app/views/companies/_form.html.erb
<%= simple_form_for(@company, :html => { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: 'Company Name' %>
  <%= f.input :website, label: 'Company URL' %>
  <%= f.input :short_description, label: 'Company Description' %>
  <%= f.button :submit, class: "btn btn-primary" %>



<% end %>

app/views/companies/edit.html.erb
<% provide(:title, 'Edit Company') %>
<h1>Edit Company</h1>

<%= render 'form' %>

app/views/companies/index.html.erb
<% provide(:title, 'Add Company') %>
<h1>All Companies</h1>

<table class="table table-striped">
	<thead>
		<th>Name</th>
		<th>URL</th>
		<th>Descripiton</th>
		<th></th>
		<th></th>
	</thead>

	<tbody>
		<%= render @companies %>
	</tbody>
</table>

app/views/companies/new.html.erb
<% provide(:title, 'Add Company') %>
<h1>Add a New Company</h1>

app/views/companies/show.html.erb
<% provide(:title, @company.name) %>
<h1><%= @company.name %></h1>
<div class="well">
<table class="table table-hover">
	<thead>
		<th>Name</th>
		<th>URL</th>
		<th>Description</th>
		<th></th>
	</thead>
	<tbody>
		<td><%= link_to @company.name, @company %></td>
		<td><%= @company.website %></td>
		<td><%= @company.short_description %></td>
		<% if current_associate.admin? %>
			<td><%= link_to 'Edit', edit_company_path(@company) %></td>
	    <td><%= link_to 'Delete', @company, method: :delete, data: { confirm: "You sure?" } %></td>
  	<% end %>
	</tbody>
</table>
</div>

<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Searches</a></li>
    <li><a href="#tab2" data-toggle="tab">Locations</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
    	<% if !@company.searches.empty? %>
      <table class="table table-striped">
				<thead>
					<th>Company</th>
					<th>Position</th>
				</thead>
				<tbody>
					<%= render @searches %>
				</tbody>
			</table>
			<% end %>
    </div>
    <div class="tab-pane" id="tab2">
    	<% if !@company.locations.empty? %>
      <table class="table table-striped">
      	<thead>
					<th>Name</th>
					<th>Address</th>
					<!--<th>Address 2</th>-->
					<th>City</th>
					<th>State</th>
					<th>Zip Code</th>
					<th>Country</th>
					<th>Phone</th>
				</thead>
				<tbody>
					<%= render @locations %>
				</tbody>
			</table>
			<% else %>
				<%= link_to 'You must add a location.', new_location_path %>
			<% end %>
    </div>
  </div>
</div>