config/routes.rb
Dp::Application.routes.draw do

resources :groups
resources :associates
resources :companies
resources :locations
resources :searches
resources :sessions, only: [:new, :create, :destroy]

root :to => "pages#home"

match '/team', to: 'pages#team'
match '/offices', to: 'pages#offices'
match '/signin', to: 'sessions#new'
match '/signup',  to: 'associates#new'
match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/associate.rb
class Associate < ActiveRecord::Base
  attr_accessible :admin, :bio, :email, :group_id, :name, :password, :password_confirmation
  has_secure_password
  belongs_to :group
  has_many :searches

  before_save { |associate| associate.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
  
end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController
  before_filter :signed_in_associate, only: [:index, :edit, :update, :destroy]
  before_filter :correct_associate,   only: [:edit, :update]
  before_filter :admin_associate,     only: :destroy

  def new
  	@associate = Associate.new
  end

  def show
  	@associate = Associate.find(params[:id])
    @searches = @associate.searches

  end

  def index
  	@associates = Associate.all
  end

  def edit
  end

  def create
    @associate = Associate.new(params[:associate])
    if @associate.save
      sign_in @associate
      flash[:success] = "Welcome to Daversa Partners!"
      redirect_to @associate
    else
      render 'new'
    end
  end

  def update
    if @associate.update_attributes(params[:associate])
      flash[:success] = "Profile updated"
      sign_in @associate
      redirect_to @associate
    else
      render 'edit'
    end
  end

  def destroy
    Associate.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to associates_url
  end

  private

      def signed_in_associate
        unless signed_in?
          store_location
          redirect_to signin_url, notice: "Please sign in."
        end
      end

      def correct_associate
      @associate = Associate.find(params[:id])
      redirect_to(root_path) unless current_associate?(@associate)
      end

      def admin_associate
      redirect_to(root_path) unless current_associate.admin?
      end

  
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/views/associates/_associate.html.erb
<tr>
	<td><%= link_to associate.name, associate %></td>
	<td><%= associate.email %></td>
	<td><%= (associate.searches.count) %></td>
	<td><%= link_to associate.group.name, associate.group(associate) %></td>
	<td><%= link_to 'Show', associate %></td>
	<% if current_associate.admin? %>
		<td><%= link_to 'Edit', edit_associate_path(associate) %></td>
    <td><%= link_to 'Delete', associate, method: :delete, data: { confirm: "You sure?" } %></td>
  <% end %>
</tr>

app/views/associates/_form.html.erb
<%= simple_form_for(@associate, :html => { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %> 
  <%= f.input :email %>
  <%= f.input :bio %>
  <%= f.input :password %>
  <%= f.input :password_confirmation, label: 'Password Confirmation' %>
  <%= f.button :submit, label: 'Update', class: "btn btn-primary" %>

<% end %>

app/views/associates/edit.html.erb
<% provide(:title, 'Edit Associate') %>
<h1>Edit Associate</h1>

<%= render 'form' %>

app/views/associates/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Associates</h1>
<table class="table table-striped">
	<thead>
		<th>Name</th>
		<th>Email</th>
		<th>Searches</th>
		<th>Team</th>
		<th></th>
	</thead>

	<tbody>
		<%= render @associates %>
	</tbody>
</table>

app/views/associates/new.html.erb
<% provide(:title, 'New Associate') %>
<h1>New Associate</h1>

<%= simple_form_for(@associate, :html => { class: 'form-horizontal' }) do |f| %>
  <%= f.input :name %> 
  <%= f.input :email %>
  <%= f.association :group, as: :radio_buttons, label: 'Partner' %>
  <%= f.input :password %>
  <%= f.input :password_confirmation, label: 'Password Confirmation' %>
  <%= f.button :submit, label: 'Create', class: "btn btn-primary" %>

  <%= f.error_notification %>

<% end %>

app/views/associates/show.html.erb
<% provide(:title, @associate.name) %>
<h1><%= @associate.name %></h1>
<div class="well">
	<table class="table table-hover">
		<thead>
			<th>Name</th>
			<th>Email</th>
			<th>Bio</th>
			<th>Team</th>
		</thead>
		<tbody>
			<td><%= link_to @associate.name, edit_associate_path(@associate) %></td>
			<td><%= @associate.email %></td>
			<td><%= @associate.bio %></td>
			<td><%= link_to @associate.group.name, @associate.group %></td>
		</tbody>
	</table>
</div>


<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab"><%= @associate.name %>'s Searches (<%= @associate.searches.count %>)</a></li>
    <li><a href="#tab2" data-toggle="tab">Analytics</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
    	<% if !@associate.searches.empty? %>
      <table class="table table-striped">
				<thead>
					<th>Client</th>
					<th>Position</th>
				</thead>
				<tbody>
					<%= render @searches %>
				</tbody>
			</table>
			<% else %>
				<%= link_to 'Add a new search!', new_search_path %>
			<% end %>
    </div>
    <div class="tab-pane" id="tab2">
      <table class="table table-striped">
				<tbody>
					<p>Analytics go here.</p>
				</tbody>
			</table>
    </div>
  </div>
</div>