config/routes.rb
Dp::Application.routes.draw do

resources :groups
resources :associates
resources :companies
resources :locations
resources :searches
resources :sessions, only: [:new, :create, :destroy]

root :to => "pages#home"

match '/team', to: 'pages#team'
match '/offices', to: 'pages#offices'
match '/signin', to: 'sessions#new'
match '/signup',  to: 'associates#new'
match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Daversa Partners", root_path, class: "brand" %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to 'Groups', groups_path %></li>
          <li><%= link_to 'Clients', companies_path %></li>
          <li><%= link_to 'Searches', searches_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Add Company', new_company_path %></li>
              <li><%= link_to 'Add Search', new_search_path %></li>
              <li><%= link_to 'Something Else Here', "#" %></li>
              <li class="divider"></li>
              <li class="nav-header">Nav header</li>
              <li><%= link_to "Edit My Profile", "#" %></li>
            </ul>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
      	<ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "My Profile", current_associate %></li>
            <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Login", signin_path %></li>
          <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div id="wrap">
			<title>Daversa Partners | <%= yield(:title) %></title>
				<%= render 'layouts/header' %>
					<div class="container">
						<% flash.each do |key, value| %>
							<%= content_tag(:div, value, class: "alert alert-#{key}") %>
						<% end %>
						<%= yield %>
					</div>
		</div>

	<!-- Le javascript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="../assets/js/jquery.js"></script>
	<script src="../assets/js/bootstrap-transition.js"></script>
	<script src="../assets/js/bootstrap-alert.js"></script>
	<script src="../assets/js/bootstrap-modal.js"></script>
	<script src="../assets/js/bootstrap-dropdown.js"></script>
	<script src="../assets/js/bootstrap-scrollspy.js"></script>
	<script src="../assets/js/bootstrap-tab.js"></script>
	<script src="../assets/js/bootstrap-tooltip.js"></script>
	<script src="../assets/js/bootstrap-popover.js"></script>
	<script src="../assets/js/bootstrap-button.js"></script>
	<script src="../assets/js/bootstrap-collapse.js"></script>
	<script src="../assets/js/bootstrap-carousel.js"></script>
	<script src="../assets/js/bootstrap-typeahead.js"></script>

	</body>
</html>